name: Deploy to ECR

on: 
  push:
    branches: [ prod ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build and push images to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        APP_ECR_REPOSITORY: appecr
        DB_ECR_REPOSITORY: dbecr
        TAG_APP_Manish: v0-app
        TAG_DB_Manish:  v0-db
      

      run: |
        cd application/app/
        docker build -t $ECR_REGISTRY/${APP_ECR_REPOSITORY}:${TAG_APP_Manish} -f Dockerfile .
        docker push $ECR_REGISTRY/${APP_ECR_REPOSITORY}:${TAG_APP_Manish}
        cd ../db
        docker build -t $ECR_REGISTRY/${DB_ECR_REPOSITORY}:${TAG_DB_Manish} -f Dockerfile_mysql .
        docker push $ECR_REGISTRY/${DB_ECR_REPOSITORY}:${TAG_DB_Manish}
        
